plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.6.1'
}

group = 'com.colsson'
version = '0.8.0'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
    maven { url = uri("https://repo.aikar.co/nexus/content/groups/aikar/") }
    maven { url = uri("https://libraries.minecraft.net/") }
    maven { url = uri("https://repo.papermc.io/maven/public/") }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.4-R0.1-SNAPSHOT'
    implementation 'com.zaxxer:HikariCP:5.1.0'
    implementation 'com.mysql:mysql-connector-j:9.2.0'

    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.xerial:sqlite-jdbc:3.46.0.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

shadowJar {
    archiveClassifier.set('')
    archiveBaseName.set('Beacon')
    archiveVersion.set('0.8.0')

    dependencies {
        exclude(dependency('io.papermc.paper:paper-api:.*'))
    }
}

build.dependsOn shadowJar
