name: Beacon
version: 1.0.0
main: com.colsson.beacon.BeaconPlugin
api-version: '1.21'
description: Sistema de permisos, grupos y herencia
author: Colsson
commands:
  beacon:
    description: Comando principal de Beacon
    usage: /beacon <subcomando>
    aliases: [b, bc]
permissions:
  beacon.admin:
    description: Permite usar todos los comandos de Beacon
    default: op
